@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "examples.dataflow.adapter.WebServiceAdapter#restMethod(Request)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "examples.dataflow",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": false,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "TypesAndMethods", // TypesOnly, MethodsOnly, TypesAndMethods
    "showDetailedClassStructure": true
  },
  "rootClass": "examples.dataflow.adapter.WebServiceAdapter"
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1150508209 { 
   	label=adapter
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Request686937538[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Request</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   id: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Response686937538[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Response</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   id: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

subgraph cluster_1502206846 { 
   	label=WebServiceAdapter
	labeljust=l
	fillcolor=white
	style=filled
   
   WebServiceAdapter686937538XXXrestMethod1534621073[
	label="+ restMethod()"
	style=filled
	fillcolor=white
	tooltip="WebServiceAdapter

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_1326197564 { 
   	label=domain
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Entity895601675[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Entity</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   id: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

subgraph cluster_1479269788 { 
   	label=Service
	labeljust=l
	fillcolor=white
	style=filled
   
   Service895601675XXXloadById1808118735[
	label="+ loadById()"
	style=filled
	fillcolor=white
	tooltip="Service

null"
	fontcolor=darkgreen
];
} 
} 

'edges    
Service895601675XXXloadById1808118735 -> Entity895601675[label=return, style=dashed];
WebServiceAdapter686937538XXXrestMethod1534621073 -> Request686937538[label=request, style=dashed];
WebServiceAdapter686937538XXXrestMethod1534621073 -> Response686937538[label=return, style=dashed];
WebServiceAdapter686937538XXXrestMethod1534621073 -> Service895601675XXXloadById1808118735;
    
}
@enduml
